# Generated by Django 4.2 on 2023-04-07 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('Gender', models.CharField(max_length=1)),
                ('medical_history', models.TextField()),
                ('A', models.BooleanField()),
                ('B', models.BooleanField()),
                ('Rh', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_collection', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_used', models.PositiveIntegerField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bms.donor')),
            ],
        ),
    ]
